### ISSUE TITLE
Link in README.md is not working

### ISSUE THREAD

**Issue by joaand** [Eman2000/Arduino-BMS#1]
Should be:
https://www.youtube.com/watch?v=MRjxQVYBM_k&list=PLKs13xje3QqQ0RkARzCQ8lr5z54pQdRd_

**Comment by Eman2000** [comment]
Changed the link to this one:
https://www.youtube.com/watch?v=MRjxQVYBM_k&list=PLKs13xje3QqQ0RkARzCQ8lr5z54pQdRd_&t=0s&index=2

Should work now
